### ISSUE TITLE
client cannot hear firesound

### ISSUE THREAD

**Issue by Alexander5421** [Unity-Technologies/com.unity.multiplayer.samples.bitesize#125]
**Describe the bug**
The client fires a bullet, but only the host can hear the firesound.

 https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/blob/6e39bc28f5a1ef51f49324e9d46897e118adbd77/Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs#LL197C26-L197C26
I think this line causes the bug. Fire action is a FireServerRpc, So only the host executes this function.

**Comment by Alexander5421** [comment]
This is my solution
`
 [ClientRpc]
    void PlayFireSoundClientRpc()
    {
        fireSound.Play();
    }
`
and replace the `fireSound.Play();` with PlayFireSoundClientRpc();

**Comment by fernando-cortez** [comment]
Hi @Alexander5421 ,
This work has landed into our workflows in this [PR](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/pull/148), and so I'll close this issue.

Thanks again for your contribution!
