### ISSUE TITLE
why m_Thrusting is a NetworkVariable but m_spin is not?

### ISSUE THREAD

**Issue by Alexander5421** [Unity-Technologies/com.unity.multiplayer.samples.bitesize#128]
https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/blob/6e39bc28f5a1ef51f49324e9d46897e118adbd77/Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs#L110-L112

m_Thrusting is never used on the client side, what's the point to sync it to clients?

**Comment by fernando-cortez** [comment]
Hi @Alexander5421,
Yes, you're correct. This replicated variable `m_Thrusting` isn't used client-side, and can be converted to just a float.

We'll get that converted over!
