### ISSUE TITLE
MMO type game

### ISSUE THREAD

**Issue by CODEHUBHQ** [Unity-Technologies/com.unity.multiplayer.samples.bitesize#242]
It would be great if we can have an example MMO using NGOs
A good example would be similar to [uMMORPG Remastered - MMORPG Engine](https://assetstore.unity.com/packages/templates/systems/ummorpg-remastered-mmorpg-engine-159401)

of course not the same asset, as it would be complex to do, however a good project structure and basic features would be great

**Comment by hershbansal99** [comment]
Thanks for the suggestion @CODEHUBHQ. We'll take a closer look and see if something like this can be added to our samples roadmap.
