### ISSUE TITLE
enemies not showing up when joining an inprogress game

### ISSUE THREAD

**Issue by cutopia** [Unity-Technologies/com.unity.multiplayer.samples.bitesize#28]
**Describe the bug**
Joining a game already playing in a session results in the enemies not showing up. Bullets rain down still, however.

**To Reproduce**
1. Build the game and run twice.
2. Have first copy of game host
3. second copy joins localhost game
4. run a third copy of the game
5. have third copy join localhost

**Expected behavior**
I would expect the game to be fully recreated for the late joiner, allowing them to see all the graphical elements the other two clients see.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Unity Version: 2020.3.12f1
 - MLAPI Version: 0.1.0
 - Bitesize Samples Repository Version/Commit https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/commit/3dc3c39f8a9e5de91c544fefd78188cc739143d5

**Comment by LPLafontaineB** [comment]
This seems to have been partially fixed in the develop branch. Now, enemies are properly replicated as well as bullets, but not the player characters. Will look into this further
