### ISSUE TITLE
2DSpaceShooter asteroids spawning from objectpool with kinematics enabled in rigidbody2d.

### ISSUE THREAD

**Issue by bradyb90** [Unity-Technologies/com.unity.multiplayer.samples.bitesize#45]
**Describe the bug**

Run in Host (Server + Client).

Shoot an asteroid. 

in public void ReturnNetworkObject(NetworkObject networkObject, GameObject prefab) place the following code in the function with a breakpoint on the assert.

        if (networkObject.name.Contains("Asteroid") && networkObject.GetComponent<Rigidbody2D>().isKinematic)
        {
            Assert.IsFalse(GetComponent<Rigidbody2D>().isKinematic);
        }

observe that the gameobjects rigidbody2d is now kinematic for some reason. Seems to be a bug in the Unity.Netcode between Asteroid:Explode() and DummyPrefabInstanceHandler:Destroy.

**Expected behavior**
Asteroid prefab would still have its settings on the object.

**Screenshots**

**Environment (please complete the following information):**
 - OS:Windows 10
 - Unity Version: 2020.3.27f1
 - MLAPI Version: [e.g. v6.0.1] ?? where do you see this? Nothing with that title is in package manager.
 - Bitesize Samples Repository Version/Commit  commit b00c067deeb81939ec366a3d5705ae9952475438

**Comment by LPLafontaineB** [comment]
Hi @bradyb90 , I managed to reproduce this bug using commit b00c067deeb81939ec366a3d5705ae9952475438, but not on the develop branch. This was likely caused by an NGO issue that has been fixed since.
